// GICS sub-industry name -> 8-digit code lookup.
// Source: MSCI/S&P Global Industry Classification Standard (2023 revision),
// transcribed from the public Wikipedia GICS reference list.
// Yahoo Finance's `industry` field generally reports the GICS sub-industry name.
//
// Names are normalized via `normalize()` for matching: lowercase, ASCII letters/digits only.

const GICS_SUB_INDUSTRIES = {
  // 10 Energy
  10101010: 'Oil & Gas Drilling',
  10101020: 'Oil & Gas Equipment & Services',
  10102010: 'Integrated Oil & Gas',
  10102020: 'Oil & Gas Exploration & Production',
  10102030: 'Oil & Gas Refining & Marketing',
  10102040: 'Oil & Gas Storage & Transportation',
  10102050: 'Coal & Consumable Fuels',
  // 15 Materials
  15101010: 'Commodity Chemicals',
  15101020: 'Diversified Chemicals',
  15101030: 'Fertilizers & Agricultural Chemicals',
  15101040: 'Industrial Gases',
  15101050: 'Specialty Chemicals',
  15102010: 'Construction Materials',
  15103010: 'Metal, Glass & Plastic Containers',
  15103020: 'Paper & Plastic Packaging Products & Materials',
  15104010: 'Aluminum',
  15104020: 'Diversified Metals & Mining',
  15104025: 'Copper',
  15104030: 'Gold',
  15104040: 'Precious Metals & Minerals',
  15104045: 'Silver',
  15104050: 'Steel',
  15105010: 'Forest Products',
  15105020: 'Paper Products',
  // 20 Industrials
  20101010: 'Aerospace & Defense',
  20102010: 'Building Products',
  20103010: 'Construction & Engineering',
  20104010: 'Electrical Components & Equipment',
  20104020: 'Heavy Electrical Equipment',
  20105010: 'Industrial Conglomerates',
  20106010: 'Construction Machinery & Heavy Transportation Equipment',
  20106015: 'Agricultural & Farm Machinery',
  20106020: 'Industrial Machinery & Supplies & Components',
  20107010: 'Trading Companies & Distributors',
  20201010: 'Commercial Printing',
  20201050: 'Environmental & Facilities Services',
  20201060: 'Office Services & Supplies',
  20201070: 'Diversified Support Services',
  20201080: 'Security & Alarm Services',
  20202010: 'Human Resource & Employment Services',
  20202020: 'Research & Consulting Services',
  20202030: 'Data Processing & Outsourced Services',
  20301010: 'Air Freight & Logistics',
  20302010: 'Passenger Airlines',
  20303010: 'Marine Transportation',
  20304010: 'Rail Transportation',
  20304030: 'Cargo Ground Transportation',
  20304040: 'Passenger Ground Transportation',
  20305010: 'Airport Services',
  20305020: 'Highways & Railtracks',
  20305030: 'Marine Ports & Services',
  // 25 Consumer Discretionary
  25101010: 'Automotive Parts & Equipment',
  25101020: 'Tires & Rubber',
  25102010: 'Automobile Manufacturers',
  25102020: 'Motorcycle Manufacturers',
  25201010: 'Consumer Electronics',
  25201020: 'Home Furnishings',
  25201030: 'Homebuilding',
  25201040: 'Household Appliances',
  25201050: 'Housewares & Specialties',
  25202010: 'Leisure Products',
  25203010: 'Apparel, Accessories & Luxury Goods',
  25203020: 'Footwear',
  25203030: 'Textiles',
  25301010: 'Casinos & Gaming',
  25301020: 'Hotels, Resorts & Cruise Lines',
  25301030: 'Leisure Facilities',
  25301040: 'Restaurants',
  25302010: 'Education Services',
  25302020: 'Specialized Consumer Services',
  25401010: 'Distributors',
  25503030: 'Broadline Retail',
  25504010: 'Apparel Retail',
  25504020: 'Computer & Electronics Retail',
  25504030: 'Home Improvement Retail',
  25504040: 'Other Specialty Retail',
  25504050: 'Automotive Retail',
  25504060: 'Homefurnishing Retail',
  // 30 Consumer Staples
  30101010: 'Drug Retail',
  30101020: 'Food Distributors',
  30101030: 'Food Retail',
  30101040: 'Consumer Staples Merchandise Retail',
  30201010: 'Brewers',
  30201020: 'Distillers & Vintners',
  30201030: 'Soft Drinks & Non-alcoholic Beverages',
  30202010: 'Agricultural Products & Services',
  30202030: 'Packaged Foods & Meats',
  30203010: 'Tobacco',
  30301010: 'Household Products',
  30302010: 'Personal Care Products',
  // 35 Health Care
  35101010: 'Health Care Equipment',
  35101020: 'Health Care Supplies',
  35102010: 'Health Care Distributors',
  35102015: 'Health Care Services',
  35102020: 'Health Care Facilities',
  35102030: 'Managed Health Care',
  35103010: 'Health Care Technology',
  35201010: 'Biotechnology',
  35202010: 'Pharmaceuticals',
  35203010: 'Life Sciences Tools & Services',
  // 40 Financials
  40101010: 'Diversified Banks',
  40101015: 'Regional Banks',
  40201020: 'Diversified Financial Services',
  40201030: 'Multi-Sector Holdings',
  40201040: 'Specialized Finance',
  40201050: 'Commercial & Residential Mortgage Finance',
  40201060: 'Transaction & Payment Processing Services',
  40202010: 'Consumer Finance',
  40203010: 'Asset Management & Custody Banks',
  40203020: 'Investment Banking & Brokerage',
  40203030: 'Diversified Capital Markets',
  40203040: 'Financial Exchanges & Data',
  40204010: 'Mortgage REITs',
  40301010: 'Insurance Brokers',
  40301020: 'Life & Health Insurance',
  40301030: 'Multi-line Insurance',
  40301040: 'Property & Casualty Insurance',
  40301050: 'Reinsurance',
  // 45 Information Technology
  45102010: 'IT Consulting & Other Services',
  45102020: 'Internet Services & Infrastructure',
  45103010: 'Application Software',
  45103020: 'Systems Software',
  45201020: 'Communications Equipment',
  45202030: 'Technology Hardware, Storage & Peripherals',
  45203010: 'Electronic Equipment & Instruments',
  45203015: 'Electronic Components',
  45203020: 'Electronic Manufacturing Services',
  45203030: 'Technology Distributors',
  45301010: 'Semiconductor Materials & Equipment',
  45301020: 'Semiconductors',
  // 50 Communication Services
  50101010: 'Alternative Carriers',
  50101020: 'Integrated Telecommunication Services',
  50102010: 'Wireless Telecommunication Services',
  50201010: 'Advertising',
  50201020: 'Broadcasting',
  50201030: 'Cable & Satellite',
  50201040: 'Publishing',
  50202010: 'Movies & Entertainment',
  50202020: 'Interactive Home Entertainment',
  50203010: 'Interactive Media & Services',
  // 55 Utilities
  55101010: 'Electric Utilities',
  55102010: 'Gas Utilities',
  55103010: 'Multi-Utilities',
  55104010: 'Water Utilities',
  55105010: 'Independent Power Producers & Energy Traders',
  55105020: 'Renewable Electricity',
  // 60 Real Estate
  60101010: 'Diversified REITs',
  60102510: 'Industrial REITs',
  60103010: 'Hotel & Resort REITs',
  60104010: 'Office REITs',
  60105010: 'Health Care REITs',
  60106010: 'Multi-Family Residential REITs',
  60106020: 'Single-Family Residential REITs',
  60107010: 'Retail REITs',
  60108010: 'Other Specialized REITs',
  60108020: 'Self-Storage REITs',
  60108030: 'Telecom Tower REITs',
  60108040: 'Timber REITs',
  60108050: 'Data Center REITs',
  60201010: 'Diversified Real Estate Activities',
  60201020: 'Real Estate Operating Companies',
  60201030: 'Real Estate Development',
  60201040: 'Real Estate Services',
};

const normalize = (s) => (s || '').toLowerCase().replace(/[^a-z0-9]+/g, '');

const NAME_TO_CODE = {};
for (const [code, name] of Object.entries(GICS_SUB_INDUSTRIES)) {
  NAME_TO_CODE[normalize(name)] = code;
}

// Common Yahoo-name to GICS-name aliases.
const ALIASES = {
  [normalize('Auto Parts')]: normalize('Automotive Parts & Equipment'),
  [normalize('Auto Manufacturers')]: normalize('Automobile Manufacturers'),
  [normalize('Software—Application')]: normalize('Application Software'),
  [normalize('Software - Application')]: normalize('Application Software'),
  [normalize('Software—Infrastructure')]: normalize('Systems Software'),
  [normalize('Software - Infrastructure')]: normalize('Systems Software'),
  [normalize('Banks—Diversified')]: normalize('Diversified Banks'),
  [normalize('Banks - Diversified')]: normalize('Diversified Banks'),
  [normalize('Banks—Regional')]: normalize('Regional Banks'),
  [normalize('Banks - Regional')]: normalize('Regional Banks'),
  [normalize('Internet Content & Information')]: normalize('Interactive Media & Services'),
  [normalize('Internet Retail')]: normalize('Broadline Retail'),
  [normalize('Discount Stores')]: normalize('Consumer Staples Merchandise Retail'),
  [normalize('Drug Manufacturers—General')]: normalize('Pharmaceuticals'),
  [normalize('Drug Manufacturers - General')]: normalize('Pharmaceuticals'),
  [normalize('Drug Manufacturers—Specialty & Generic')]: normalize('Pharmaceuticals'),
  [normalize('Medical Devices')]: normalize('Health Care Equipment'),
  [normalize('Medical Instruments & Supplies')]: normalize('Health Care Supplies'),
  [normalize('Medical Care Facilities')]: normalize('Health Care Facilities'),
  [normalize('Medical Distribution')]: normalize('Health Care Distributors'),
  [normalize('Diagnostics & Research')]: normalize('Life Sciences Tools & Services'),
  [normalize('Healthcare Plans')]: normalize('Managed Health Care'),
  [normalize('Insurance—Property & Casualty')]: normalize('Property & Casualty Insurance'),
  [normalize('Insurance - Property & Casualty')]: normalize('Property & Casualty Insurance'),
  [normalize('Insurance—Life')]: normalize('Life & Health Insurance'),
  [normalize('Insurance - Life')]: normalize('Life & Health Insurance'),
  [normalize('Insurance—Diversified')]: normalize('Multi-line Insurance'),
  [normalize('Insurance - Diversified')]: normalize('Multi-line Insurance'),
  [normalize('Insurance—Specialty')]: normalize('Multi-line Insurance'),
  [normalize('Insurance—Reinsurance')]: normalize('Reinsurance'),
  [normalize('Insurance Brokers')]: normalize('Insurance Brokers'),
  [normalize('Capital Markets')]: normalize('Investment Banking & Brokerage'),
  [normalize('Asset Management')]: normalize('Asset Management & Custody Banks'),
  [normalize('Credit Services')]: normalize('Transaction & Payment Processing Services'),
  [normalize('Financial Data & Stock Exchanges')]: normalize('Financial Exchanges & Data'),
  [normalize('Information Technology Services')]: normalize('IT Consulting & Other Services'),
  [normalize('Semiconductor Equipment & Materials')]: normalize('Semiconductor Materials & Equipment'),
  [normalize('Computer Hardware')]: normalize('Technology Hardware, Storage & Peripherals'),
  [normalize('REIT—Industrial')]: normalize('Industrial REITs'),
  [normalize('REIT—Office')]: normalize('Office REITs'),
  [normalize('REIT—Retail')]: normalize('Retail REITs'),
  [normalize('REIT—Residential')]: normalize('Multi-Family Residential REITs'),
  [normalize('REIT—Healthcare Facilities')]: normalize('Health Care REITs'),
  [normalize('REIT—Hotel & Motel')]: normalize('Hotel & Resort REITs'),
  [normalize('REIT—Mortgage')]: normalize('Mortgage REITs'),
  [normalize('REIT—Specialty')]: normalize('Other Specialized REITs'),
  [normalize('REIT—Diversified')]: normalize('Diversified REITs'),
  [normalize('Telecom Services')]: normalize('Integrated Telecommunication Services'),
  [normalize('Entertainment')]: normalize('Movies & Entertainment'),
  [normalize('Specialty Retail')]: normalize('Other Specialty Retail'),
  [normalize('Apparel Manufacturing')]: normalize('Apparel, Accessories & Luxury Goods'),
  [normalize('Luxury Goods')]: normalize('Apparel, Accessories & Luxury Goods'),
  [normalize('Beverages—Non-Alcoholic')]: normalize('Soft Drinks & Non-alcoholic Beverages'),
  [normalize('Beverages—Brewers')]: normalize('Brewers'),
  [normalize('Beverages—Wineries & Distilleries')]: normalize('Distillers & Vintners'),
  [normalize('Packaged Foods')]: normalize('Packaged Foods & Meats'),
  [normalize('Farm Products')]: normalize('Agricultural Products & Services'),
  [normalize('Grocery Stores')]: normalize('Food Retail'),
  [normalize('Pharmaceutical Retailers')]: normalize('Drug Retail'),
  [normalize('Travel Services')]: normalize('Hotels, Resorts & Cruise Lines'),
  [normalize('Resorts & Casinos')]: normalize('Casinos & Gaming'),
  [normalize('Lodging')]: normalize('Hotels, Resorts & Cruise Lines'),
  [normalize('Gambling')]: normalize('Casinos & Gaming'),
  [normalize('Recreational Vehicles')]: normalize('Leisure Products'),
  [normalize('Furnishings, Fixtures & Appliances')]: normalize('Home Furnishings'),
  [normalize('Residential Construction')]: normalize('Homebuilding'),
  [normalize('Building Products & Equipment')]: normalize('Building Products'),
  [normalize('Engineering & Construction')]: normalize('Construction & Engineering'),
  [normalize('Specialty Industrial Machinery')]: normalize('Industrial Machinery & Supplies & Components'),
  [normalize('Farm & Heavy Construction Machinery')]: normalize('Construction Machinery & Heavy Transportation Equipment'),
  [normalize('Tools & Accessories')]: normalize('Industrial Machinery & Supplies & Components'),
  [normalize('Electrical Equipment & Parts')]: normalize('Electrical Components & Equipment'),
  [normalize('Pollution & Treatment Controls')]: normalize('Environmental & Facilities Services'),
  [normalize('Waste Management')]: normalize('Environmental & Facilities Services'),
  [normalize('Staffing & Employment Services')]: normalize('Human Resource & Employment Services'),
  [normalize('Consulting Services')]: normalize('Research & Consulting Services'),
  [normalize('Specialty Business Services')]: normalize('Diversified Support Services'),
  [normalize('Security & Protection Services')]: normalize('Security & Alarm Services'),
  [normalize('Rental & Leasing Services')]: normalize('Trading Companies & Distributors'),
  [normalize('Integrated Freight & Logistics')]: normalize('Air Freight & Logistics'),
  [normalize('Trucking')]: normalize('Cargo Ground Transportation'),
  [normalize('Railroads')]: normalize('Rail Transportation'),
  [normalize('Airlines')]: normalize('Passenger Airlines'),
  [normalize('Airports & Air Services')]: normalize('Airport Services'),
  [normalize('Marine Shipping')]: normalize('Marine Transportation'),
  [normalize('Utilities—Regulated Electric')]: normalize('Electric Utilities'),
  [normalize('Utilities - Regulated Electric')]: normalize('Electric Utilities'),
  [normalize('Utilities—Regulated Gas')]: normalize('Gas Utilities'),
  [normalize('Utilities - Regulated Gas')]: normalize('Gas Utilities'),
  [normalize('Utilities—Regulated Water')]: normalize('Water Utilities'),
  [normalize('Utilities - Regulated Water')]: normalize('Water Utilities'),
  [normalize('Utilities—Diversified')]: normalize('Multi-Utilities'),
  [normalize('Utilities - Diversified')]: normalize('Multi-Utilities'),
  [normalize('Utilities—Independent Power Producers')]: normalize('Independent Power Producers & Energy Traders'),
  [normalize('Utilities—Renewable')]: normalize('Renewable Electricity'),
  [normalize('Oil & Gas Integrated')]: normalize('Integrated Oil & Gas'),
  [normalize('Oil & Gas E&P')]: normalize('Oil & Gas Exploration & Production'),
  [normalize('Oil & Gas Midstream')]: normalize('Oil & Gas Storage & Transportation'),
  [normalize('Oil & Gas Equipment & Services')]: normalize('Oil & Gas Equipment & Services'),
  [normalize('Oil & Gas Drilling')]: normalize('Oil & Gas Drilling'),
  [normalize('Oil & Gas Refining & Marketing')]: normalize('Oil & Gas Refining & Marketing'),
  [normalize('Thermal Coal')]: normalize('Coal & Consumable Fuels'),
};

export function lookupGicsCode(industryName) {
  if (!industryName) return null;
  const key = normalize(industryName);
  const aliased = ALIASES[key] || key;
  return NAME_TO_CODE[aliased] || null;
}
